### ISSUE TITLE
caffeinate gets suspended when being executed from the battery widget.

### ISSUE THREAD

**Issue by HeySora** [Jean-Tinland/simple-bar#133]
When clicking on the battery widget, a `caffeinate` instance gets spawned. However, it seems to be suspended soon after it's started.
- If the battery widget realizes that and hides the caffeinate state, clicking again will spawn another instance of `caffeinate`.
- If the widget is clicked fast enough (the caffeinate state is still shown), the suspended instance will be killed as expected.

In any case, none of the `caffeinate` processes will prevent sleep in this state, making this feature useless.

Demo video with a live `ps aux | grep -i caffeinate` running:
https://user-images.githubusercontent.com/17962248/119263551-ca3c9080-bbdf-11eb-8ccf-34b50c2aa492.mov

I am using a M1 MacBook Air running Big Sur 11.3.1 (20E241).

**Comment by Jean-Tinland** [comment]
Are you observing the same behaviour if you launch manually `caffeinate` in your terminal?

It looks like something is systematically killing the process. I can't reproduce the issue for now (on my Intel mbp).

**Comment by HeySora** [comment]
Launching `caffeinate` from the Terminal doesn't show this behavior. (And the battery widget updates its appearance accordingly! The coffee icon shows by itself)
Also yes, this seems to be a M1-specific issue, I don't have that issue on an Intel Mac.

**Comment by HeySora** [comment]
@Jean-Tinland FYI I opened an issue directly on Übersicht's GitHub repo, as simply running `run('caffeinate &')` exhibits this behavior.

Hoping it can be resolved quickly!

**Comment by HeySora** [comment]
I discovered that running `arch -arch x86_64 caffeinate` does not work either on Apple Silicon.
Übersicht being an x86_64 program, running `caffeinate` would launch it as x86_64 by default.

`run('arch -arch arm64 caffeinate &')` works for Apple Silicon computers.

After quickly experimenting, here are my findings:

- `uname -m` returns `arm64` under a regular Terminal. However it returns `x86_64` for a Rosetta app.
- `uname -a` under a Rosetta app shows `Darwin <hostname> 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 x86_64`

Under bash, something like this would work:

```bash
appleSilicon=false
if [[ "$(uname -m)" = arm64 || "$(uname -m)" = x86_64* && "$(uname -a)" = *ARM64* ]]; then
    appleSilicon=true
fi
```

**Comment by Jean-Tinland** [comment]
I updated the battery widget in order to check the system before launching the caffeinate command. It should now work as expected.

**Comment by HeySora** [comment]
It still does not work, and the reason is because you're only checking for `uname -m`.

![image](https://user-images.githubusercontent.com/17962248/142932863-d1dbae33-8522-4de8-8ac5-716f4b8f72e2.png)

I wrote here that this was not enough, you need to use `uname -a` as well!

> After quickly experimenting, here are my findings:
> 
> * `uname -m` returns `arm64` under a regular Terminal. However it returns `x86_64` for a Rosetta app.
> * `uname -a` under a Rosetta app shows `Darwin <hostname> 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 x86_64`, notice the presence of "ARM64" in the full kernel name despite the arch still being "x86_64"
> 
> Under bash, something like this would work:
> 
> ```shell
> appleSilicon=false
> if [[ "$(uname -m)" = arm64* || "$(uname -m)" = x86_64* && "$(uname -a)" = *ARM64* ]]; then
>     appleSilicon=true
> fi
> ```

**Comment by Jean-Tinland** [comment]
Indeed, sorry for reading your message a bit to fast!

I implemented this logic according to your message:

```javascript
export const getSystem = async () => {
  const [bareArchitecture, bareSystem] = await Promise.all([Uebersicht.run('uname -a'), Uebersicht.run('uname -m')])
  const architecture = cleanupOutput(bareArchitecture)
  const system = cleanupOutput(bareSystem)
  if (system.endsWith('arm64') || (system.endsWith('x86_64') && architecture.includes('ARM64'))) {
    return 'arm64'
  }
  return 'x86_64'
}
```

Let me know if this is working as expected. :)

**Comment by HeySora** [comment]
It's alright, you probably have a ton of things to do! Thank you again for your hard work 🙏

It's working perfectly now, thank you so much! However there is a tiny (I promise 😅) edit to do:

I would replace the 2 `system.endsWith()` calls with `system.startsWith()`, because Apple is going to use `'arm64e'` in the near future, which would break your current code if someone uses an arm64 / arm64e version of Übersicht instead of a Rosetta one.

**Comment by Jean-Tinland** [comment]
Indeed, I changed `endsWith` with `startsWith`:)

Thank you for your valuable inputs!
