### ISSUE TITLE
aerospace spaces on wrong monitor

### ISSUE THREAD

**Issue by bin101** [Jean-Tinland/simple-bar#440]
**Describe the bug**
Installed and configured simplebar today and having the exact same issue as in #434 but for aerospace

**Expected behavior**
Aerospace space should be shown on the corresponding monitor

**Screenshots**
n/a

**Information (please complete the following information):**

- OS version 15.3.1
- aerospace --version 
aerospace CLI client version: 0.16.2-Beta 21336ad382539b35fdc94b4fbd55408e10b101f8
AeroSpace.app server version: 0.16.2-Beta 21336ad382539b35fdc94b4fbd55408e10b101f8
- Übersicht version 1.6 (82)

**Comment by Jean-Tinland** [comment]
How many external screen are you using?

It seems that depending on your display positioning, numbering is not done the same way between AeroSpace and Übersicht.

On my part, I'm using only my mac book native screen with a single external screen and everything is working the way it's intended.

I'll try to reproduce the issue and see what I can do :)

**Comment by bin101** [comment]
I use the native mac book display and 2 further external monitors

**Comment by mauricekraus** [comment]
This also occurs with just two external monitors. However after a restart of ubersicht, the issue is resolved.

**Comment by mauricekraus** [comment]
I take it back, i need a restart now

**Comment by FormalSnake** [comment]
I have the same issue
My spaces for the 2nd monitor are shown on the 1st monitor, and the spaces specific to the 1st monitor are shown on the 2nd
The spaces on the small monitor should be shown on the ultrawide

![Image](https://github.com/user-attachments/assets/d93c9b85-4e6c-421a-91cc-754ea3b2daa9)

<img width="1180" alt="Image" src="https://github.com/user-attachments/assets/e6967169-ff1d-4fe0-8184-7445e4dfbba2" />

**Comment by MatsHaby** [comment]
I’m experiencing the same issue with spaces on the opposite screen when using AeroSpace. I haven’t found a solution yet.”

**Comment by Jean-Tinland** [comment]
Unfortunately, I don't think I can automatically solve this!

One way to circumvent the problem would be to let the user make the match between Übersicht display numbering and AeroSpace's in `simple-bar` settings. Would this work?

I'll keep you posted as soon as possible!

**Comment by FormalSnake** [comment]
> Unfortunately, I don't think I can automatically solve this!
> 
> One way to circumvent the problem would be to let the user make the match between Übersicht display numbering and AeroSpace's in `simple-bar` settings. Would this work?
> 
> I'll keep you posted as soon as possible!

I think a solution like that should work.
Maybe also an invert ordering button might work, but idk how that would handle 3 or more monitors

**Comment by bin101** [comment]
@Jean-Tinland the following command will return the appkit screen ids if it helps you:

`aerospace list-workspaces --all --format '%{workspace}%{monitor-appkit-nsscreen-screens-id}' --json`

In my case:
```
[
  {
    "workspace" : "web",
    "monitor-appkit-nsscreen-screens-id" : 3
  },
  {
    "workspace" : "code",
    "monitor-appkit-nsscreen-screens-id" : 1
  },
  {
    "monitor-appkit-nsscreen-screens-id" : 2,
    "workspace" : "misc"
  }
]
```

**Comment by MatsHaby** [comment]
I did some testing, and it seems like `parseInt(window.location.pathname.replace("/", ""), 10);` counts my Mac’s screen even when it’s closed, while Aerospace does not. This could cause a mismatch.

I haven’t tested this extensively, but it works in my current setup with just two external monitors.

```
[
  {
    "monitor-appkit-nsscreen-screens-id" : 1,
    "monitor-id" : 1,
    "monitor-name" : "MSI MAG342CQR"
  },
  {
    "monitor-id" : 2,
    "monitor-appkit-nsscreen-screens-id" : 2,
    "monitor-name" : "P34w-20"
  }
]
```


My change in simple-bar-context.jsx
```  // still counts built-in Retina Display even if aerospace does not
  const displayId = parseInt(window.location.pathname.replace("/", ""), 10);

  // Check if the built-in Retina Display is present in the current displays
  const hasBuiltinRetina = currentDisplays.some(
    (d) => d["monitor-name"] === "Built-in Retina Display",
  );

  // Adjust displayId if the Retina screen is missing
  const adjustedDisplayId = hasBuiltinRetina ? displayId : displayId - 1;

  // Find the current display based on the adjusted display ID
  const currentDisplay =
    currentDisplays?.find((d) => {
      const id = d["monitor-appkit-nsscreen-screens-id"] ?? d.id;
      return id === adjustedDisplayId;
    }) || {};
```

**Comment by dubbe** [comment]
`parseInt(window.location.pathname.replace("/", ""), 10);` doesn't seem to work at all for me. It says 3 for both my displays (1 and 2).

**Comment by mauricekraus** [comment]
@dubbe i observed that while the debug console does say 3 (2 in my case) for all monitors, when you directly print this number to the bars (by early return a <div>{id}<\div>, it correctly assigns the numbers to the monitors. However this makes it extremely difficult to debug.

**Comment by MatsHaby** [comment]
I did notice that you have to open a debug window on each monitor to get correct output 😅

**Comment by dubbe** [comment]
@MatsHaby ah, I have to do some more digging later. But a bit weird that I get a 3 when aerospace uses 1 and 2.

**Comment by mauricekraus** [comment]
@MatsHaby  how does it work? When i click on übersicht in the toolbar, it directly opens two debug windows, both with screenid 2, and only  one shows any activity (i guess the main one)

following 
https://github.com/felixhageloh/uebersicht/issues/235

i.e. http://127.0.0.1:41416/<screenid> (1 in my case) doesnt work at all and i only get the warning, that yabai is not running.

**Comment by Jean-Tinland** [comment]
> I did some testing, and it seems like `parseInt(window.location.pathname.replace("/", ""), 10);` counts my Mac’s screen even when it’s closed, while Aerospace does not. This could cause a mismatch.
> ....

@MatsHaby thanks a lot! I wasn't aware of that.

I just pushed on master with these changes, please anyone let me know if this solves this issue!

As for working with the Übersicht console, it must indeed be opened on the right display in order to log data correctly! The console has two windows: one for "background" and another one for "foreground" widgets. `simple-bar` should be located on foreground by default.

**Comment by dubbe** [comment]
Thanks, it still shows my (only) external display as 3 from parseInt(window.location.pathname.replace("/", ""), 10);

aerospace list-monitors outputs
`1 | Built-in Retina Display
2 | DELL P3223QE`

**Comment by MatsHaby** [comment]
I believe the issue originates from Aerospace. It seems like their method for fetching monitor IDs is causing the problem, and fixing it would likely resolve this issue as well.

I wasn’t able to open an issue on their repo, but I did start a discussion thread:

🔗 [Aerospace Discussion](https://github.com/nikitabobko/AeroSpace/discussions/1208)

**Comment by mauricekraus** [comment]
Is there a fix? its very annoying to manually change the ids.

**Comment by Jean-Tinland** [comment]
As of now, no. I'm afraid I'll have to add an option in settings allowing the user to manually make the association between AeroSpace spaces & Übersicht spaces. It will be better than nothing.

I'll keep you posted when I'm done with it :)

**Comment by Jean-Tinland** [comment]
I'm closing this as displays can now be arranged in any way with this setting.
