### ISSUE TITLE
Doesn't work if yabai is not installed in /usr/local/bin

### ISSUE THREAD

**Issue by duckpuppy** [Jean-Tinland/simple-bar#63]
I use Nix to manage my MacBook, and it doesn't install things to /usr/local/bin. It would be awesome if there was a way to inject the yabai path into the scripts rather than it being hard-coded to `/usr/local/bin/yabai`, even if that remains the default.

**Comment by Jean-Tinland** [comment]
I'll try to replace the hardcoded path with `which yabai` tomorrow.

It would look like that in all files using yabai:
```shell
$(which yabai) -m query --spaces
```

**Comment by Jean-Tinland** [comment]
I pushed this modification, tell me if it is working for you or not.

**Comment by duckpuppy** [comment]
OK, I'll try it out. I may have to modify the application path so that Ubersicht gets the right paths for that approach to work, but I can do that.

For anyone else finding this, the command on your mac to fix the paths so that yabai can be found is:
```
sudo launchctl config user path /path/to/yabai/bin/directory:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
That will add the new directory to the list that non-shell-based GUI apps search.

**Comment by duckpuppy** [comment]
Updating the path for user apps didn't work - Ubersicht still can't see the path I need, or there's some other issue. Manually editing the yabai calls in lib/yabai.js and the shell scripts to point to it's location on my machine does work. I'm OK with saying that I'm in the minority of users, and I'll modify my behavior to use this if I want to. The change for this issue should likely be rolled back if it works for the majority of users.

**Comment by duckpuppy** [comment]
OK, I've fixed it with the current change. Even though Ubersicht is a user-land app, the `run` function is using the system level app path. Updating it to contain the yabai path works.

So, the proper command to add the non-standard yabai path for this change would be:
```
sudo launchctl config system path /path/to/yabai/bin/directory:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

I'm still thinking that allowing the yabai binary path to be changed via the simple-bar settings might be more user-friendly.

**Comment by Jean-Tinland** [comment]
Thanks for you research, I think I'll implement a setting which will permit user to override default yabai path as you suggested it.

**Comment by Jean-Tinland** [comment]
The latest version of simple-bar includes a setting which allow the user to set his own custom path:
<img width="669" alt="image" src="https://user-images.githubusercontent.com/43068795/101241461-73f19900-36f6-11eb-8dc5-fc5093baca54.png">

**Comment by duckpuppy** [comment]
Just tried this out, works perfectly. Thanks!
